### ISSUE TITLE
Strange Behaviour?

### ISSUE THREAD

**Issue by gooly** [pylorak/reloadmatic#10]
Here [https://www.mql5.com/de/forum](url) I get an empty page if I (opt: "remember & smart timinge") reload the page (e.g. reload now) but not here: [https://www.mql5.com/en/forum](url).
It doesn't matter whether I use disable cache or not.
If go long enough back I can see the page normally again. 

=========    Addendum   ============
PS: I have to add that now everything works fine again previously the page was just white but the source code of the page seems to have arrived. 

Now it happens again :) 
If I click on the default button to reload the page I am asked by a popup window if  I want to resent the request...

**Comment by pylorak** [comment]
In my tests it worked perfectly, but I wasn't logged in and I didn't try posting in the forum.
My hunch is that the problem might have something to do with POST data, but I am still investigating.

**Comment by gooly** [comment]
I just experienced it again.
To you want me something do (log, ...)? Just let me know!

**Comment by pylorak** [comment]
No need to do anything yet. I will make experiments myself, just give me some time.

**Comment by gooly** [comment]
Ok - you are the boss :)

**Comment by gooly** [comment]
You wrote:
> In my tests it worked perfectly, but I wasn't logged in and I didn't try posting in the forum.
My hunch is that the problem might have something to do with POST data, but I am still investigating.

But the being logged in on the English site [https://github.com/pylorak/reloadmatic/issues/url](url)
works but not the German site [https://github.com/pylorak/reloadmatic/issues/url](url).
Soi I guess its not POST but its an issue of the language of the page.

**Comment by pylorak** [comment]
Okay, I can reproduce the issue. Now looking at what is causing it...

**Comment by pylorak** [comment]
I believe the problem occured for you right after Firefox upgraded the addon when I released a new version. Since the problem only appeared when reloading a web page the first time after an installation (and the addon upgrade logic before that which was supposed to prevent such situations was non-functional), you most times didn't see the error, and after a plugin upgrade it went away as soon as the page was loaded fresh.

The basic explanation is that when the plugin gets loaded into an already running Firefox, since it just got loaded, it does not have all the necessary information needed to reload existing tabs, because it couldn't listen to them when they got loaded (because at that time the plugin wasn't loaded yet). So ReloadMatic tries to make a guess in this case, and this guess didn't work for the given web page. I now changed what is guessed, but hopefully the upgrade logic was already fixed enough in 1.5.0 so that you wouldn't have seen the bug in the future again anyway. Still, the fix is good for anybody installing the plugin for the first time.

Fix on GitHub, and it will be part of 1.5.1 officially when it is released.

**Comment by pylorak** [comment]
1.5.1 is now released with the fix inside.

**Comment by gooly** [comment]
:)
I tried it (v.1.5.1) with 1 minute to have an immediate result and still get the blank page - soryy but the problem is not solved, at least not for me :(

**Comment by pylorak** [comment]
No problem. It just means what I've found wasn't the only problem :) I will need to create an account though and see then, because now with 1.5.1 I am unable to reproduce the issue. So maybe after I login.

**Comment by gooly** [comment]
Thanks but be aware of the fact that the English site: [https://www.mql5.com**/en/**forum](url) works perfectly
but not the German one: [https://www.mql5.com**/de/**forum](url).
But you cane use for both the same login!

**Comment by gooly** [comment]
Now there is another site with the same issue: a blank page after a reload of your "Reload" :(
The link has the following structure: https://www.post.at/sendungsverfolgung.php/details?pnum1=102163...
It provides me with the actual status of a packet to be delivered. 
Sorry but due to probably private information of that page I don't post the correct number!
If you enter an invalid number you end up on a page with general information: https://www.post.at/sendungsverfolgung.php that can be reloaded by your Add-On without an problem.
So I guess it is a systematic problem of you Add-On - I hope you can sort it out soon.
Thanks and a successful 2018 for you!

**Comment by gooly** [comment]
Hi and thanks!
I just noticed that the German site now can be reloaded - but the other German site [https://www.post.at/sendungsverfolgung.php](url) not :(
Sorry for that - but **thanks a lot** for the other one!!

**Comment by allanlaal** [comment]
maybe the OP could edit the title to be a little bit less generic and more descriptive of this issue? ;)
